### ISSUE TITLE
Change default datetime values

### ISSUE THREAD

**Issue by aure2006** [NB-Core/lotgd#1]
Newer MySQL versions have Strict SQL Mode enabled by default which causes many tables to not be created. Would "1970-01-01 00:00:01" be a good choice?

Edit: The default value of news.newsdate also needs to be changed.

**Comment by NB-Core** [comment]
I know, I run Ubuntu 16.04. with Mysql 5.7 and PHP7 right now (changes made in the code now).

I configured my mysql to still allow the ZERO_DATE and the TRANSIENT_TABLE values:
[mysqld]
sql_mode = ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

I haven't gotten around (due to the UTF_8 collation migration of fields in the tables) to check all for better default values. =/

**Comment by NB-Core** [comment]
I replaced in the current update (only core, not the modules yet) two new myDefine()s:
DATETIME_DATEMIN
DATETIME_DATEMAX

DATETIME_DATEMIN is by default 1970-01-01 00:00:00, the other 2159-01-01 00:00:00 (i.e. for ban expirations who are "permantent").

I installed a new fresh mysql server with default restrictions on Ubuntu 18.04 and it works.
If there are issues, please let me know.
